### ISSUE TITLE
No change to anchor styles in category section at bottom of posts on hover

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/murrow.wsu.edu#131]
![screen shot 2017-09-12 at 12 33 49 pm](https://user-images.githubusercontent.com/286171/30344569-b323194c-97b6-11e7-88fd-e7f9a6f2b8d2.png)

**Comment by philcable** [comment]
I'll pitch in with this one here - the anchor styles for categories at the bottom of posts pulled in via content syndicate could use a bit of help, too.

![syndicate-items](https://user-images.githubusercontent.com/6403569/30398546-b555fdb8-9885-11e7-96d3-3f36b789a04b.png)
