### ISSUE TITLE
Pull people profiles into search results

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/murrow.wsu.edu#59]
* [x] Upddate [WSUWP Search plugin](https://github.com/washingtonstateuniversity/WSUWP-Plugin-Search/) to support other post types.
* [x] Enable support for the people post type in the Murrow theme.
* [x] Ensure [WSUWP Search](https://github.com/washingtonstateuniversity/WSUWP-Plugin-Search/blob/master/includes/class-wsu-search.php#L138) knows how to populate post content with profile bio data.

**Comment by jeremyfelt** [comment]
@slocker3 is this a list of people attached to a post in the search results or is it searching full profiles in addition to posts/pages?

**Comment by slocker3** [comment]
@jeremyfelt that is a good question. The original thought was it would search their name and full profile and populate them in the search result.

**Comment by jeremyfelt** [comment]
Cool, we need to adjust our plugin for Elasticsearch to start storing the data so it can be searched. Once that's good, it should be pretty doable.

**Comment by jeremyfelt** [comment]
Part 3 is ongoing in #69

**Comment by jeremyfelt** [comment]
People are now indexed in search and being retrieved as part of the search results.
