### ISSUE TITLE
Add Bruce Pinkleton's people card to sidebar of Dean's page

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/murrow.wsu.edu#68]
[https://stage.murrow.wsu.edu/about/leadership-mission/deans-message/](https://stage.murrow.wsu.edu/about/leadership-mission/deans-message/)

What does this short code look like?

**Comment by philcable** [comment]
@slocker3 It would be `[wsuwp_person_card name="Bruce Pinkleton" nid="pink" /]` in this case.

If you click the `Add Post Element` button above the TinyMCE editor, there's a `Person Card` option that will walk you through adding the shortcode. However, it seems to be a bit flawed, so maybe just copy and paste the complete shortcode above for now :)

**Comment by slocker3** [comment]
👍 @philcable thank you!
Is there an option to display a simple card minus the bio?

**Comment by philcable** [comment]
@slocker3 Not currently - but we can always add more attributes for customizing the display.

If you can think of any other options that might be needed, feel free to add an issue with those at https://github.com/washingtonstateuniversity/WSU-People-Directory/issues.

**Comment by slocker3** [comment]
@philcable 👍 🥇
