### ISSUE TITLE
Layout of Directory page

### ISSUE THREAD

**Issue by allenjohns** [washingtonstateuniversity/murrow.wsu.edu#7]
Profile on page above associated posts

**Comment by philcable** [comment]
The draft design for an individual profile has been implemented -
 https://stage.murrow.wsu.edu/people/bruce-pinkleton/!

@allenjohns We'll also need a design for the page that lists all people https://stage.murrow.wsu.edu/about/people/.

**Comment by philcable** [comment]
This is done.
