### ISSUE TITLE
People profile embed is populating header with h1

### ISSUE THREAD

**Issue by slocker3** [washingtonstateuniversity/murrow.wsu.edu#91]
Example: [https://stage.murrow.wsu.edu/about/leadership-mission/deans-message/](stage.murrow.wsu.edu/about/leadership-mission/deans-message/)

Without knowing where an embed of a profile might be added, we should rethink using a header element. Would a `div` or `span` work?

```
<div class="person-name">Jolene Smith</div>
```

**Comment by philcable** [comment]
Fixed in https://github.com/washingtonstateuniversity/WSU-People-Directory/commit/f775ab0b662d40f2898db3eadb00f25130609f22. The new markup is:

`<header class="name">Jolene Smith</header>`
